from pydantic import BaseModel, Field
from datetime import datetime


class NoteCreate(BaseModel):
    """
    INPUT schema for creating a new note.

    The client sends: { "title": "My Note", "content": "This is the content." }
    The client does NOT send: id, user_id, created_at, updated_at
    Those are generated by the server/database.
    """
    title: str
    content: str
    tags: list[str] = Field(default_factory=list)

class NoteResponse(BaseModel):
    """
    OUTPUT schema for returning a note to the client.

    from_attributes = True tells Pydantic:
    "You'll receive a SQLAlchemy Note object, not a dictionary.
     Read its attributes (note.id, note.title) instead of dict keys."
    """
    id: int
    user_id: int
    title: str
    content: str
    tags: list[str] = Field(default_factory=list)
    is_pinned: bool = False
    created_at: datetime
    updated_at: datetime | None = None  # None because it's null until first update

    class Config:
        from_attributes = True

class NoteUpdate(BaseModel):
    """
    INPUT schema for updating an existing note.

    The client can send either or both fields to update:
    { "title": "Updated Title" }
    { "content": "Updated content." }
    { "title": "New Title", "content": "New content." }

    All fields are optional because the client might want to update just one.
    """
    title: str | None = None
    content: str | None = None
    tags: list[str] | None = None
