from pydantic import BaseModel
from datetime import datetime


class UserCreate(BaseModel):
    """
    INPUT schema — what the client sends to POST /auth/register

    The client sends:      { "name": "Vivek", "email": "vivek@test.com", "password": "abc123" }
    The client does NOT send: id, role, created_at, hashed_password
    Those are generated by the server/database.

    Pydantic will REJECT the request if any of these fields are missing
    or if they're the wrong type (e.g., sending a number for email).
    """
    name: str
    email: str
    password: str  # plain text — we'll hash it before storing


class UserLogin(BaseModel):
    """
    INPUT schema — what the client sends to POST /auth/login

    Just email + password. The server looks up the user,
    verifies the password, and returns a JWT token.
    """
    email: str
    password: str


class UserResponse(BaseModel):
    """
    OUTPUT schema — what the API sends BACK to the client.

    Notice: NO hashed_password field here!
    This is exactly WHY we have separate schemas for input vs output.
    The model has hashed_password, but the response schema hides it.

    from_attributes = True tells Pydantic:
    "You'll receive a SQLAlchemy User object, not a dictionary.
     Read its attributes (user.id, user.name) instead of dict keys."
    """
    id: int
    name: str
    email: str
    role: str
    created_at: datetime
    updated_at: datetime | None = None  # None because it's null until first update

    class Config:
        from_attributes = True